### ISSUE TITLE
fuel consumption graphs keep on expanding in height.

### ISSUE THREAD

**Issue by Max-Z80** [linuxserver/Clarkson#11]
After I entered some random values, the fuel consumption graph keeps on expanding in height, apparently one pixel at a time. Maybe related, the cpu resource consumption is very high when the dashboard is displayed. 
Bug occurs on firefox 52.7.3. Is it because my browser is too old ?

**Comment by Max-Z80** [comment]
Actually the monthly cost graph has the same bug.
EDIT: Same pb with firefox 63.0

**Comment by JoshStark** [comment]
I'd observed this issue before and had assumed I'd fixed it! Using random data with a large range seems to have been a good way of driving this bug back out. I've spotted your PR so will try to review it when I can. Thanks.
