### ISSUE TITLE
Incorrect MPG Calculation

### ISSUE THREAD

**Issue by dzirkler** [linuxserver/Clarkson#20]
While I would love to get this kind of mileage from this car, it's just not right... All of the mpg calculations are incorrect. 

Example:
![image](https://user-images.githubusercontent.com/10255175/63385475-e3067b00-c355-11e9-9371-fa79a6cebef2.png)

240 miles divided by 10.65 gallons = 22.54 mpg, not the 27.06 displayed.

**Comment by JoshStark** [comment]
Thanks, I'll double check the conversion rates.

**Comment by dzirkler** [comment]
I took a peek at the code that calculates, and didn't see anything immediate, so it's likely in one of the conversions. I use Miles and Gallons. They aren't all that far off, but they're all slightly higher than they should be.

**Comment by JoshStark** [comment]
Ah I think I've found the issue. It looks like I'm converting the internal fuel unit into imperial gallons when calculating the consumption rate (rather than US gals). 

I'll try to get that fixed in the next couple of days. Sorry about that! Once the fix is in, it should derive the correct values for you.

**Comment by dzirkler** [comment]
that sounds like about the right amount for the discrepancy! Thanks for the quick find! Once i get a notification on this thread, I can pull down a copy and give it a try.

**Comment by JoshStark** [comment]
A new version has been pushed up with the correct conversion rate for US gallons. Are you able to confirm the fix? (v1.1.1).

![image](https://user-images.githubusercontent.com/4211747/63635188-98d41100-c657-11e9-9eee-950358801e0e.png)

**Comment by dzirkler** [comment]
The good news is, the MPG calcs are correct! The bad news is, I'd rather get closer to 30MPG, but it is a 10-year-old car so I'll take what I can get. :)

Thanks for the fast turnaround!
