### ISSUE TITLE
Cannot install Clarkson

### ISSUE THREAD

**Issue by PrieserMax** [linuxserver/Clarkson#37]
Hello,
I've tried installing Clarkson but failed.
I tried the instructions step by step. OS: Ubuntu Server 22.04.3 LTS
Installing NodeJS with the command from the following website:
https://deb.nodesource.com
Installing NPM via apt (sudo apt install npm)
Then running the commands from "Get the dependencies" https://github.com/linuxserver/Clarkson
It always throws errors. I don't know where I have to clone the Git repository to etc.
Is there a full guide available?
I am pretty much a noob at Linux, know some basic stuff.

Greetings from Germany
Max

**Comment by j0nnymoe** [comment]
Read the top paragraph of the readme.

**Comment by PrieserMax** [comment]
Thank you very much.
I set up Hammond now ;-)
