### ISSUE TITLE
MySQL -e environment passed, but log states password: no

### ISSUE THREAD

**Issue by triDcontrols** [linuxserver/Clarkson#7]
Hi, I created the app with the following command in docker, 

`docker run -d --net clarkson_nw --name=clarkson_app -e MYSQL_HOST=clarkson_db -e MYSQL_USERNAME=clarkson -e MYSQL_PASSWORD=secret -e ENABLE_REGISTRATIONS=false -p 3000:3000 linuxserver/clarkson`

and on app startup, I get this error, complete error is on hastebin link below. 

`
Unable to obtain Jdbc connection from DataSource (jdbc:mysql://clarkson_db:3306) for user 'clarkson': Could not connect: Access denied for user 'clarkson'@'172.27.0.3' (using password: NO)`

https://hastebin.com/putogovaqa.cs

**Comment by homerr** [comment]
Are you able to connect to the SQL instance with the username and password you've used?

Eg from the Docker host: mysql -u clarkson -p -h 172.27.0.3 clarkson_db 

Should prompt for the password you've used and if it says no your user isn't created properly

**Comment by triDcontrols** [comment]
Issue Resolved, did not pass the correct argument.
