### ISSUE TITLE
Unable to register on initial application start "Registrations are Closed" 

### ISSUE THREAD

**Issue by triDcontrols** [linuxserver/Clarkson#8]
Hi, 

Got the application installed, and tried to register initial user and get an error message that "Registrations Are Closed" I'm assuming because the ENABLE_REGISTRATIONS is set to false by default. How do I register an initial admin account?

**Comment by JoshStark** [comment]
Hi @triDcontrols, you'll need to start the application initially with ENABLE_REGISTRATIONS set to "true". Once you've created the initial admin account, restart the application without that flag. Hope this helps.

**Comment by triDcontrols** [comment]
So in the process of me doing that, I created another user, some how I didn't set the flag right and wanted to test of registration is possible,  How do I manage the users?

**Comment by JoshStark** [comment]
User management isn't baked in to the application at present. Currently the difference between an admin user and a standard user is that admins have the ability to query data for other users. To do so they'd need to know the user IDs of the users they wish to query. 

I should take some time to add in a user management page for admins to at least deal with deleting or updating status. For now, if you have access to the database, you should be able to manually set the flag in MySQL. I appreciate this isn't the most obvious of options though, sorry.

**Comment by JoshStark** [comment]
I'm currently in the process of adding an admin page for admin users so they can promote/delete users. Hopefully I'll have this done in the next couple of days.

**Comment by triDcontrols** [comment]
Awesome work, Looking forward the next release. 

Do you have a feature road map? Some features like maintenance records, insurance claims, etc.  To turn it into a personal fleet management app.

**Comment by JoshStark** [comment]
I don't actually, but please do feel free to add new issues with any ideas you have :)

**Comment by JoshStark** [comment]
@triDcontrols A new version of Clarkson has just been released. See the v1.1.0 release notes to see what's been added. This should help you manage your users more easily. Thanks.
